package sop_corba;


/**
* sop_corba/FacturaInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from factura.idl
* lunes 3 de julio de 2023 08:36:59 AM COT
*/

public interface FacturaInt extends FacturaIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FacturaInt
