module sop_corba {
    interface FacturaInt{
	struct facturaDTO {
        	string nombres;
        	string apellidos;
        	string codigoProducto;
		string nombreProducto;
        	float valorInicialOferta;
        	float ValorFinalOferta;
    	};

        boolean generarFactura(in facturaDTO datos);
    };
};