package sop_corba;


/**
* sop_corba/FacturaIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from factura.idl
* lunes 3 de julio de 2023 08:36:59 AM COT
*/

public interface FacturaIntOperations 
{
  sop_corba.FacturaIntPackage.facturaDTO generarFactura (String nombres, String apellidos, String nombreProducto, float valorInicialOferta, float ValorFinalOferta);
} // interface FacturaIntOperations
