package sop_corba.FacturaIntPackage;


/**
* sop_corba/FacturaIntPackage/facturaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from factura.idl
* lunes 3 de julio de 2023 08:36:59 AM COT
*/

public final class facturaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombres = null;
  public String apellidos = null;
  public String codigoProducto = null;
  public String nombreProducto = null;
  public float valorInicialOferta = (float)0;
  public float ValorFinalOferta = (float)0;

  public facturaDTO ()
  {
  } // ctor

  public facturaDTO (String _nombres, String _apellidos, String _codigoProducto, String _nombreProducto, float _valorInicialOferta, float _ValorFinalOferta)
  {
    nombres = _nombres;
    apellidos = _apellidos;
    codigoProducto = _codigoProducto;
    nombreProducto = _nombreProducto;
    valorInicialOferta = _valorInicialOferta;
    ValorFinalOferta = _ValorFinalOferta;
  } // ctor

} // class facturaDTO
